export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION'
export const SET_POLL_QUESTION = 'SET_POLL_QUESTION'
export const RECEIVE_QUESTION_ANSWER = 'RECEIVE_QUESTION_ANSWER'

export const SET_AUTHED_USER = 'SET_AUTHED_USER'

export const RECEIVE_USERS = 'RECEIVE_USERS'
export const RECEIVE_USER_QUESTION = 'RECEIVE_USER_QUESTION'
export const RECIEVE_USER_QUESTION_ANSWER = 'RECIEVE_USER_QUESTION_ANSWER'
