export const ROOT_URL = '/'
export const DASHBOARD_URL = '/dashboard'
export const LEADERBOARD_URL = '/leaderboard'
export const NEWQUESTION_URL = '/add'
export const LOGOUT_URL = '/logout'
export const POLLQUESTION_URL = '/questions/:questionid'
export const PAGE404_URL = '/404'